export const QUIZZ_TAKER_TOKENS = {
	ATTEMPT_REPOSITORY: Symbol.for('ATTEMPT_REPOSITORY'),
	PLAYER_REPOSITORY: Symbol.for('PLAYER_REPOSITORY'),
	RESPONSE_REPOSITORY: Symbol.for('RESPONSE_REPOSITORY'),
	ANSWER_READER: Symbol.for('ANSWER_READER'),
	GET_ALL_QUIZZ_QUERY_HANDLER: Symbol.for('GET_ALL_QUIZZ_QUERY_HANDLER'),
	GET_QUIZZ_BY_ID_QUERY_HANDLER: Symbol.for('GET_QUIZZ_BY_ID_QUERY_HANDLER'),
	GET_ALL_ANSWERS_QUERY_HANDLER: Symbol.for('GET_ALL_ANSWERS_QUERY_HANDLER'),
	GET_ANSWER_BY_ID_QUERY_HANDLER: Symbol.for('GET_ANSWER_BY_ID_QUERY_HANDLER'),
	GET_ALL_QUESTIONS_QUERY_HANDLER: Symbol.for('GET_ALL_QUESTIONS_QUERY_HANDLER'),
	GET_QUESTION_BY_ID_QUERY_HANDLER: Symbol.for('GET_QUESTION_BY_ID_QUERY_HANDLER'),
};
