export const QUIZZ_TAKER_TOKENS = {
	GET_ALL_QUIZZ_QUERY_HANDLER: Symbol.for('GET_ALL_QUIZZ_QUERY_HANDLER'),
	GET_QUIZZ_BY_ID_QUERY_HANDLER: Symbol.for('GET_QUIZZ_BY_ID_QUERY_HANDLER'),
	GET_ALL_ANSWERS_QUERY_HANDLER: Symbol.for('GET_ALL_ANSWERS_QUERY_HANDLER'),
	GET_ANSWER_BY_ID_QUERY_HANDLER: Symbol.for('GET_ANSWER_BY_ID_QUERY_HANDLER'),
	GET_ALL_QUESTIONS_QUERY_HANDLER: Symbol.for('GET_ALL_QUESTIONS_QUERY_HANDLER'),
	GET_QUESTION_BY_ID_QUERY_HANDLER: Symbol.for('GET_QUESTION_BY_ID_QUERY_HANDLER'),
};
