export const QUIZZ_CREATOR_TOKENS = {
	// Repositories
	QUIZZ_REPOSITORY: Symbol.for('QUIZZ_REPOSITORY'),
	QUESTION_REPOSITORY: Symbol.for('QUESTION_REPOSITORY'),
	ANSWER_REPOSITORY: Symbol.for('ANSWER_REPOSITORY'),

	// Command Handlers (add as we create them)
	CREATE_QUIZZ_COMMAND_HANDLER: Symbol.for('CREATE_QUIZZ_COMMAND_HANDLER'),
	UPDATE_QUIZZ_COMMAND_HANDLER: Symbol.for('UPDATE_QUIZZ_COMMAND_HANDLER'),
	DELETE_QUIZZ_COMMAND_HANDLER: Symbol.for('DELETE_QUIZZ_COMMAND_HANDLER'),
	CREATE_QUESTION_COMMAND_HANDLER: Symbol.for('CREATE_QUESTION_COMMAND_HANDLER'),
	UPDATE_QUESTION_COMMAND_HANDLER: Symbol.for('UPDATE_QUESTION_COMMAND_HANDLER'),
	DELETE_QUESTION_COMMAND_HANDLER: Symbol.for('DELETE_QUESTION_COMMAND_HANDLER'),
	CREATE_ANSWER_COMMAND_HANDLER: Symbol.for('CREATE_ANSWER_COMMAND_HANDLER'),
	UPDATE_ANSWER_COMMAND_HANDLER: Symbol.for('UPDATE_ANSWER_COMMAND_HANDLER'),
	DELETE_ANSWER_COMMAND_HANDLER: Symbol.for('DELETE_ANSWER_COMMAND_HANDLER'),
};
